package com.ernesto.perez.balancepersonal.datos.entidades;

import com.ernesto.perez.balancepersonal.daos.DaoSession;
import de.greenrobot.dao.DaoException;

import com.ernesto.perez.balancepersonal.daos.AdjuntoDDao;
import com.ernesto.perez.balancepersonal.daos.AnulacionMovDDao;
import com.ernesto.perez.balancepersonal.daos.CategoriaDDao;
import com.ernesto.perez.balancepersonal.daos.MovimientoDDao;
import com.ernesto.perez.balancepersonal.daos.OrigenFinancieroDDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table MOVIMIENTO_D.
 */
public class MovimientoD {

    private Long id;
    /** Not-null value. */
    private String concepto;
    /** Not-null value. */
    private java.util.Date fechaHora;
    private double latitud;
    private double longitud;
    private int tipoMovimiento;
    private double importe;
    private long idCategoria;
    private long idOrigenFinanciero;
    private Long idAnulacion;
    private Long idAdjunto;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient MovimientoDDao myDao;

    private AnulacionMovD anulacion;
    private Long anulacion__resolvedKey;

    private AdjuntoD adjunto;
    private Long adjunto__resolvedKey;

    private CategoriaD categoria;
    private Long categoria__resolvedKey;

    private OrigenFinancieroD movimientos;
    private Long movimientos__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MovimientoD() {
    }

    public MovimientoD(Long id) {
        this.id = id;
    }

    public MovimientoD(Long id, String concepto, java.util.Date fechaHora, double latitud, double longitud, int tipoMovimiento, double importe, long idCategoria, long idOrigenFinanciero, Long idAnulacion, Long idAdjunto) {
        this.id = id;
        this.concepto = concepto;
        this.fechaHora = fechaHora;
        this.latitud = latitud;
        this.longitud = longitud;
        this.tipoMovimiento = tipoMovimiento;
        this.importe = importe;
        this.idCategoria = idCategoria;
        this.idOrigenFinanciero = idOrigenFinanciero;
        this.idAnulacion = idAnulacion;
        this.idAdjunto = idAdjunto;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMovimientoDDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getConcepto() {
        return concepto;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }

    /** Not-null value. */
    public java.util.Date getFechaHora() {
        return fechaHora;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFechaHora(java.util.Date fechaHora) {
        this.fechaHora = fechaHora;
    }

    public double getLatitud() {
        return latitud;
    }

    public void setLatitud(double latitud) {
        this.latitud = latitud;
    }

    public double getLongitud() {
        return longitud;
    }

    public void setLongitud(double longitud) {
        this.longitud = longitud;
    }

    public int getTipoMovimiento() {
        return tipoMovimiento;
    }

    public void setTipoMovimiento(int tipoMovimiento) {
        this.tipoMovimiento = tipoMovimiento;
    }

    public double getImporte() {
        return importe;
    }

    public void setImporte(double importe) {
        this.importe = importe;
    }

    public long getIdCategoria() {
        return idCategoria;
    }

    public void setIdCategoria(long idCategoria) {
        this.idCategoria = idCategoria;
    }

    public long getIdOrigenFinanciero() {
        return idOrigenFinanciero;
    }

    public void setIdOrigenFinanciero(long idOrigenFinanciero) {
        this.idOrigenFinanciero = idOrigenFinanciero;
    }

    public Long getIdAnulacion() {
        return idAnulacion;
    }

    public void setIdAnulacion(Long idAnulacion) {
        this.idAnulacion = idAnulacion;
    }

    public Long getIdAdjunto() {
        return idAdjunto;
    }

    public void setIdAdjunto(Long idAdjunto) {
        this.idAdjunto = idAdjunto;
    }

    /** To-one relationship, resolved on first access. */
    public AnulacionMovD getAnulacion() {
        Long __key = this.idAnulacion;
        if (anulacion__resolvedKey == null || !anulacion__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            AnulacionMovDDao targetDao = daoSession.getAnulacionMovDDao();
            AnulacionMovD anulacionNew = targetDao.load(__key);
            synchronized (this) {
                anulacion = anulacionNew;
            	anulacion__resolvedKey = __key;
            }
        }
        return anulacion;
    }

    public void setAnulacion(AnulacionMovD anulacion) {
        synchronized (this) {
            this.anulacion = anulacion;
            idAnulacion = anulacion == null ? null : anulacion.getId();
            anulacion__resolvedKey = idAnulacion;
        }
    }

    /** To-one relationship, resolved on first access. */
    public AdjuntoD getAdjunto() {
        Long __key = this.idAdjunto;
        if (adjunto__resolvedKey == null || !adjunto__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            AdjuntoDDao targetDao = daoSession.getAdjuntoDDao();
            AdjuntoD adjuntoNew = targetDao.load(__key);
            synchronized (this) {
                adjunto = adjuntoNew;
            	adjunto__resolvedKey = __key;
            }
        }
        return adjunto;
    }

    public void setAdjunto(AdjuntoD adjunto) {
        synchronized (this) {
            this.adjunto = adjunto;
            idAdjunto = adjunto == null ? null : adjunto.getId();
            adjunto__resolvedKey = idAdjunto;
        }
    }

    /** To-one relationship, resolved on first access. */
    public CategoriaD getCategoria() {
        long __key = this.idCategoria;
        if (categoria__resolvedKey == null || !categoria__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            CategoriaDDao targetDao = daoSession.getCategoriaDDao();
            CategoriaD categoriaNew = targetDao.load(__key);
            synchronized (this) {
                categoria = categoriaNew;
            	categoria__resolvedKey = __key;
            }
        }
        return categoria;
    }

    public void setCategoria(CategoriaD categoria) {
        if (categoria == null) {
            throw new DaoException("To-one property 'idCategoria' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.categoria = categoria;
            idCategoria = categoria.getId();
            categoria__resolvedKey = idCategoria;
        }
    }

    /** To-one relationship, resolved on first access. */
    public OrigenFinancieroD getMovimientos() {
        long __key = this.idOrigenFinanciero;
        if (movimientos__resolvedKey == null || !movimientos__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            OrigenFinancieroDDao targetDao = daoSession.getOrigenFinancieroDDao();
            OrigenFinancieroD movimientosNew = targetDao.load(__key);
            synchronized (this) {
                movimientos = movimientosNew;
            	movimientos__resolvedKey = __key;
            }
        }
        return movimientos;
    }

    public void setMovimientos(OrigenFinancieroD movimientos) {
        if (movimientos == null) {
            throw new DaoException("To-one property 'idOrigenFinanciero' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.movimientos = movimientos;
            idOrigenFinanciero = movimientos.getId();
            movimientos__resolvedKey = idOrigenFinanciero;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
