package com.ernesto.perez.balancepersonal.datos.entidades;

import java.util.List;
import com.ernesto.perez.balancepersonal.daos.DaoSession;
import de.greenrobot.dao.DaoException;

import com.ernesto.perez.balancepersonal.daos.MovimientoDDao;
import com.ernesto.perez.balancepersonal.daos.OrigenFinancieroDDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ORIGEN_FINANCIERO_D.
 */
public class OrigenFinancieroD {

    private Long id;
    /** Not-null value. */
    private String nombre;
    private double saldo;
    private long resImagen;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient OrigenFinancieroDDao myDao;

    private List<MovimientoD> origenFinanciero;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public OrigenFinancieroD() {
    }

    public OrigenFinancieroD(Long id) {
        this.id = id;
    }

    public OrigenFinancieroD(Long id, String nombre, double saldo, long resImagen) {
        this.id = id;
        this.nombre = nombre;
        this.saldo = saldo;
        this.resImagen = resImagen;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getOrigenFinancieroDDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNombre() {
        return nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public double getSaldo() {
        return saldo;
    }

    public void setSaldo(double saldo) {
        this.saldo = saldo;
    }

    public long getResImagen() {
        return resImagen;
    }

    public void setResImagen(long resImagen) {
        this.resImagen = resImagen;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<MovimientoD> getOrigenFinanciero() {
        if (origenFinanciero == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            MovimientoDDao targetDao = daoSession.getMovimientoDDao();
            List<MovimientoD> origenFinancieroNew = targetDao._queryOrigenFinancieroD_OrigenFinanciero(id);
            synchronized (this) {
                if(origenFinanciero == null) {
                    origenFinanciero = origenFinancieroNew;
                }
            }
        }
        return origenFinanciero;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetOrigenFinanciero() {
        origenFinanciero = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
