package com.ernesto.perez.balancepersonal.daos;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.ernesto.perez.balancepersonal.entidades.Imagen;

import com.ernesto.perez.balancepersonal.entidades.Categoria;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CATEGORIA.
*/
public class CategoriaDao extends AbstractDao<Categoria, Long> {

    public static final String TABLENAME = "CATEGORIA";

    /**
     * Properties of entity Categoria.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nombre = new Property(1, String.class, "nombre", false, "NOMBRE");
        public final static Property Descripcion = new Property(2, String.class, "descripcion", false, "DESCRIPCION");
        public final static Property TipoCategoria = new Property(3, int.class, "tipoCategoria", false, "TIPO_CATEGORIA");
        public final static Property Estado = new Property(4, int.class, "estado", false, "ESTADO");
        public final static Property IdImagen = new Property(5, Long.class, "idImagen", false, "ID_IMAGEN");
    };

    private DaoSession daoSession;


    public CategoriaDao(DaoConfig config) {
        super(config);
    }
    
    public CategoriaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CATEGORIA' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'NOMBRE' TEXT NOT NULL ," + // 1: nombre
                "'DESCRIPCION' TEXT NOT NULL ," + // 2: descripcion
                "'TIPO_CATEGORIA' INTEGER NOT NULL ," + // 3: tipoCategoria
                "'ESTADO' INTEGER NOT NULL ," + // 4: estado
                "'ID_IMAGEN' INTEGER);"); // 5: idImagen
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CATEGORIA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Categoria entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getNombre());
        stmt.bindString(3, entity.getDescripcion());
        stmt.bindLong(4, entity.getTipoCategoria());
        stmt.bindLong(5, entity.getEstado());
 
        Long idImagen = entity.getIdImagen();
        if (idImagen != null) {
            stmt.bindLong(6, idImagen);
        }
    }

    @Override
    protected void attachEntity(Categoria entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Categoria readEntity(Cursor cursor, int offset) {
        Categoria entity = new Categoria( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // nombre
            cursor.getString(offset + 2), // descripcion
            cursor.getInt(offset + 3), // tipoCategoria
            cursor.getInt(offset + 4), // estado
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // idImagen
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Categoria entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNombre(cursor.getString(offset + 1));
        entity.setDescripcion(cursor.getString(offset + 2));
        entity.setTipoCategoria(cursor.getInt(offset + 3));
        entity.setEstado(cursor.getInt(offset + 4));
        entity.setIdImagen(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Categoria entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Categoria entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getImagenDao().getAllColumns());
            builder.append(" FROM CATEGORIA T");
            builder.append(" LEFT JOIN IMAGEN T0 ON T.'ID_IMAGEN'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Categoria loadCurrentDeep(Cursor cursor, boolean lock) {
        Categoria entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Imagen logo = loadCurrentOther(daoSession.getImagenDao(), cursor, offset);
        entity.setLogo(logo);

        return entity;    
    }

    public Categoria loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Categoria> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Categoria> list = new ArrayList<Categoria>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Categoria> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Categoria> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
