package com.ernesto.perez.balancepersonal.daos;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.ernesto.perez.balancepersonal.daos.ImagenDDao;
import com.ernesto.perez.balancepersonal.daos.BancoDDao;
import com.ernesto.perez.balancepersonal.daos.OrigenFinancieroDDao;
import com.ernesto.perez.balancepersonal.daos.CuentaDDao;
import com.ernesto.perez.balancepersonal.daos.CategoriaDDao;
import com.ernesto.perez.balancepersonal.daos.AdjuntoDDao;
import com.ernesto.perez.balancepersonal.daos.AnulacionMovDDao;
import com.ernesto.perez.balancepersonal.daos.MovimientoDDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        ImagenDDao.createTable(db, ifNotExists);
        BancoDDao.createTable(db, ifNotExists);
        OrigenFinancieroDDao.createTable(db, ifNotExists);
        CuentaDDao.createTable(db, ifNotExists);
        CategoriaDDao.createTable(db, ifNotExists);
        AdjuntoDDao.createTable(db, ifNotExists);
        AnulacionMovDDao.createTable(db, ifNotExists);
        MovimientoDDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        ImagenDDao.dropTable(db, ifExists);
        BancoDDao.dropTable(db, ifExists);
        OrigenFinancieroDDao.dropTable(db, ifExists);
        CuentaDDao.dropTable(db, ifExists);
        CategoriaDDao.dropTable(db, ifExists);
        AdjuntoDDao.dropTable(db, ifExists);
        AnulacionMovDDao.dropTable(db, ifExists);
        MovimientoDDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(ImagenDDao.class);
        registerDaoClass(BancoDDao.class);
        registerDaoClass(OrigenFinancieroDDao.class);
        registerDaoClass(CuentaDDao.class);
        registerDaoClass(CategoriaDDao.class);
        registerDaoClass(AdjuntoDDao.class);
        registerDaoClass(AnulacionMovDDao.class);
        registerDaoClass(MovimientoDDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
