package com.ernesto.perez.balancepersonal.daos;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ernesto.perez.balancepersonal.entidades.Imagen;
import com.ernesto.perez.balancepersonal.entidades.Banco;
import com.ernesto.perez.balancepersonal.entidades.OrigenFinanciero;
import com.ernesto.perez.balancepersonal.entidades.Cuenta;
import com.ernesto.perez.balancepersonal.entidades.Categoria;
import com.ernesto.perez.balancepersonal.entidades.Adjunto;
import com.ernesto.perez.balancepersonal.entidades.AnulacionMov;
import com.ernesto.perez.balancepersonal.entidades.Movimiento;
import com.ernesto.perez.balancepersonal.entidades.MovimientoPeriodico;
import com.ernesto.perez.balancepersonal.entidades.DetalleMovPeriodico;
import com.ernesto.perez.balancepersonal.entidades.Contacto;
import com.ernesto.perez.balancepersonal.entidades.Telefono;
import com.ernesto.perez.balancepersonal.entidades.Prestamo;
import com.ernesto.perez.balancepersonal.entidades.detallePrestamo;
import com.ernesto.perez.balancepersonal.entidades.Ajuste;
import com.ernesto.perez.balancepersonal.entidades.detalleAjuste;

import com.ernesto.perez.balancepersonal.daos.ImagenDao;
import com.ernesto.perez.balancepersonal.daos.BancoDao;
import com.ernesto.perez.balancepersonal.daos.OrigenFinancieroDao;
import com.ernesto.perez.balancepersonal.daos.CuentaDao;
import com.ernesto.perez.balancepersonal.daos.CategoriaDao;
import com.ernesto.perez.balancepersonal.daos.AdjuntoDao;
import com.ernesto.perez.balancepersonal.daos.AnulacionMovDao;
import com.ernesto.perez.balancepersonal.daos.MovimientoDao;
import com.ernesto.perez.balancepersonal.daos.MovimientoPeriodicoDao;
import com.ernesto.perez.balancepersonal.daos.DetalleMovPeriodicoDao;
import com.ernesto.perez.balancepersonal.daos.ContactoDao;
import com.ernesto.perez.balancepersonal.daos.TelefonoDao;
import com.ernesto.perez.balancepersonal.daos.PrestamoDao;
import com.ernesto.perez.balancepersonal.daos.detallePrestamoDao;
import com.ernesto.perez.balancepersonal.daos.AjusteDao;
import com.ernesto.perez.balancepersonal.daos.detalleAjusteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imagenDaoConfig;
    private final DaoConfig bancoDaoConfig;
    private final DaoConfig origenFinancieroDaoConfig;
    private final DaoConfig cuentaDaoConfig;
    private final DaoConfig categoriaDaoConfig;
    private final DaoConfig adjuntoDaoConfig;
    private final DaoConfig anulacionMovDaoConfig;
    private final DaoConfig movimientoDaoConfig;
    private final DaoConfig movimientoPeriodicoDaoConfig;
    private final DaoConfig detalleMovPeriodicoDaoConfig;
    private final DaoConfig contactoDaoConfig;
    private final DaoConfig telefonoDaoConfig;
    private final DaoConfig prestamoDaoConfig;
    private final DaoConfig detallePrestamoDaoConfig;
    private final DaoConfig ajusteDaoConfig;
    private final DaoConfig detalleAjusteDaoConfig;

    private final ImagenDao imagenDao;
    private final BancoDao bancoDao;
    private final OrigenFinancieroDao origenFinancieroDao;
    private final CuentaDao cuentaDao;
    private final CategoriaDao categoriaDao;
    private final AdjuntoDao adjuntoDao;
    private final AnulacionMovDao anulacionMovDao;
    private final MovimientoDao movimientoDao;
    private final MovimientoPeriodicoDao movimientoPeriodicoDao;
    private final DetalleMovPeriodicoDao detalleMovPeriodicoDao;
    private final ContactoDao contactoDao;
    private final TelefonoDao telefonoDao;
    private final PrestamoDao prestamoDao;
    private final detallePrestamoDao detallePrestamoDao;
    private final AjusteDao ajusteDao;
    private final detalleAjusteDao detalleAjusteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imagenDaoConfig = daoConfigMap.get(ImagenDao.class).clone();
        imagenDaoConfig.initIdentityScope(type);

        bancoDaoConfig = daoConfigMap.get(BancoDao.class).clone();
        bancoDaoConfig.initIdentityScope(type);

        origenFinancieroDaoConfig = daoConfigMap.get(OrigenFinancieroDao.class).clone();
        origenFinancieroDaoConfig.initIdentityScope(type);

        cuentaDaoConfig = daoConfigMap.get(CuentaDao.class).clone();
        cuentaDaoConfig.initIdentityScope(type);

        categoriaDaoConfig = daoConfigMap.get(CategoriaDao.class).clone();
        categoriaDaoConfig.initIdentityScope(type);

        adjuntoDaoConfig = daoConfigMap.get(AdjuntoDao.class).clone();
        adjuntoDaoConfig.initIdentityScope(type);

        anulacionMovDaoConfig = daoConfigMap.get(AnulacionMovDao.class).clone();
        anulacionMovDaoConfig.initIdentityScope(type);

        movimientoDaoConfig = daoConfigMap.get(MovimientoDao.class).clone();
        movimientoDaoConfig.initIdentityScope(type);

        movimientoPeriodicoDaoConfig = daoConfigMap.get(MovimientoPeriodicoDao.class).clone();
        movimientoPeriodicoDaoConfig.initIdentityScope(type);

        detalleMovPeriodicoDaoConfig = daoConfigMap.get(DetalleMovPeriodicoDao.class).clone();
        detalleMovPeriodicoDaoConfig.initIdentityScope(type);

        contactoDaoConfig = daoConfigMap.get(ContactoDao.class).clone();
        contactoDaoConfig.initIdentityScope(type);

        telefonoDaoConfig = daoConfigMap.get(TelefonoDao.class).clone();
        telefonoDaoConfig.initIdentityScope(type);

        prestamoDaoConfig = daoConfigMap.get(PrestamoDao.class).clone();
        prestamoDaoConfig.initIdentityScope(type);

        detallePrestamoDaoConfig = daoConfigMap.get(detallePrestamoDao.class).clone();
        detallePrestamoDaoConfig.initIdentityScope(type);

        ajusteDaoConfig = daoConfigMap.get(AjusteDao.class).clone();
        ajusteDaoConfig.initIdentityScope(type);

        detalleAjusteDaoConfig = daoConfigMap.get(detalleAjusteDao.class).clone();
        detalleAjusteDaoConfig.initIdentityScope(type);

        imagenDao = new ImagenDao(imagenDaoConfig, this);
        bancoDao = new BancoDao(bancoDaoConfig, this);
        origenFinancieroDao = new OrigenFinancieroDao(origenFinancieroDaoConfig, this);
        cuentaDao = new CuentaDao(cuentaDaoConfig, this);
        categoriaDao = new CategoriaDao(categoriaDaoConfig, this);
        adjuntoDao = new AdjuntoDao(adjuntoDaoConfig, this);
        anulacionMovDao = new AnulacionMovDao(anulacionMovDaoConfig, this);
        movimientoDao = new MovimientoDao(movimientoDaoConfig, this);
        movimientoPeriodicoDao = new MovimientoPeriodicoDao(movimientoPeriodicoDaoConfig, this);
        detalleMovPeriodicoDao = new DetalleMovPeriodicoDao(detalleMovPeriodicoDaoConfig, this);
        contactoDao = new ContactoDao(contactoDaoConfig, this);
        telefonoDao = new TelefonoDao(telefonoDaoConfig, this);
        prestamoDao = new PrestamoDao(prestamoDaoConfig, this);
        detallePrestamoDao = new detallePrestamoDao(detallePrestamoDaoConfig, this);
        ajusteDao = new AjusteDao(ajusteDaoConfig, this);
        detalleAjusteDao = new detalleAjusteDao(detalleAjusteDaoConfig, this);

        registerDao(Imagen.class, imagenDao);
        registerDao(Banco.class, bancoDao);
        registerDao(OrigenFinanciero.class, origenFinancieroDao);
        registerDao(Cuenta.class, cuentaDao);
        registerDao(Categoria.class, categoriaDao);
        registerDao(Adjunto.class, adjuntoDao);
        registerDao(AnulacionMov.class, anulacionMovDao);
        registerDao(Movimiento.class, movimientoDao);
        registerDao(MovimientoPeriodico.class, movimientoPeriodicoDao);
        registerDao(DetalleMovPeriodico.class, detalleMovPeriodicoDao);
        registerDao(Contacto.class, contactoDao);
        registerDao(Telefono.class, telefonoDao);
        registerDao(Prestamo.class, prestamoDao);
        registerDao(detallePrestamo.class, detallePrestamoDao);
        registerDao(Ajuste.class, ajusteDao);
        registerDao(detalleAjuste.class, detalleAjusteDao);
    }
    
    public void clear() {
        imagenDaoConfig.getIdentityScope().clear();
        bancoDaoConfig.getIdentityScope().clear();
        origenFinancieroDaoConfig.getIdentityScope().clear();
        cuentaDaoConfig.getIdentityScope().clear();
        categoriaDaoConfig.getIdentityScope().clear();
        adjuntoDaoConfig.getIdentityScope().clear();
        anulacionMovDaoConfig.getIdentityScope().clear();
        movimientoDaoConfig.getIdentityScope().clear();
        movimientoPeriodicoDaoConfig.getIdentityScope().clear();
        detalleMovPeriodicoDaoConfig.getIdentityScope().clear();
        contactoDaoConfig.getIdentityScope().clear();
        telefonoDaoConfig.getIdentityScope().clear();
        prestamoDaoConfig.getIdentityScope().clear();
        detallePrestamoDaoConfig.getIdentityScope().clear();
        ajusteDaoConfig.getIdentityScope().clear();
        detalleAjusteDaoConfig.getIdentityScope().clear();
    }

    public ImagenDao getImagenDao() {
        return imagenDao;
    }

    public BancoDao getBancoDao() {
        return bancoDao;
    }

    public OrigenFinancieroDao getOrigenFinancieroDao() {
        return origenFinancieroDao;
    }

    public CuentaDao getCuentaDao() {
        return cuentaDao;
    }

    public CategoriaDao getCategoriaDao() {
        return categoriaDao;
    }

    public AdjuntoDao getAdjuntoDao() {
        return adjuntoDao;
    }

    public AnulacionMovDao getAnulacionMovDao() {
        return anulacionMovDao;
    }

    public MovimientoDao getMovimientoDao() {
        return movimientoDao;
    }

    public MovimientoPeriodicoDao getMovimientoPeriodicoDao() {
        return movimientoPeriodicoDao;
    }

    public DetalleMovPeriodicoDao getDetalleMovPeriodicoDao() {
        return detalleMovPeriodicoDao;
    }

    public ContactoDao getContactoDao() {
        return contactoDao;
    }

    public TelefonoDao getTelefonoDao() {
        return telefonoDao;
    }

    public PrestamoDao getPrestamoDao() {
        return prestamoDao;
    }

    public detallePrestamoDao getDetallePrestamoDao() {
        return detallePrestamoDao;
    }

    public AjusteDao getAjusteDao() {
        return ajusteDao;
    }

    public detalleAjusteDao getDetalleAjusteDao() {
        return detalleAjusteDao;
    }

}
