package com.ernesto.perez.balancepersonal.daos;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.ernesto.perez.balancepersonal.entidades.Movimiento;
import com.ernesto.perez.balancepersonal.entidades.Prestamo;

import com.ernesto.perez.balancepersonal.entidades.detallePrestamo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DETALLE_PRESTAMO.
*/
public class detallePrestamoDao extends AbstractDao<detallePrestamo, Long> {

    public static final String TABLENAME = "DETALLE_PRESTAMO";

    /**
     * Properties of entity detallePrestamo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdPrestamo = new Property(1, long.class, "idPrestamo", false, "ID_PRESTAMO");
        public final static Property IdMovimiento = new Property(2, long.class, "idMovimiento", false, "ID_MOVIMIENTO");
    };

    private DaoSession daoSession;

    private Query<detallePrestamo> prestamo_MovimientosQuery;
    private Query<detallePrestamo> movimiento_PrestamosQuery;

    public detallePrestamoDao(DaoConfig config) {
        super(config);
    }
    
    public detallePrestamoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DETALLE_PRESTAMO' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'ID_PRESTAMO' INTEGER NOT NULL ," + // 1: idPrestamo
                "'ID_MOVIMIENTO' INTEGER NOT NULL );"); // 2: idMovimiento
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DETALLE_PRESTAMO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, detallePrestamo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIdPrestamo());
        stmt.bindLong(3, entity.getIdMovimiento());
    }

    @Override
    protected void attachEntity(detallePrestamo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public detallePrestamo readEntity(Cursor cursor, int offset) {
        detallePrestamo entity = new detallePrestamo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // idPrestamo
            cursor.getLong(offset + 2) // idMovimiento
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, detallePrestamo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdPrestamo(cursor.getLong(offset + 1));
        entity.setIdMovimiento(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(detallePrestamo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(detallePrestamo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "movimientos" to-many relationship of Prestamo. */
    public List<detallePrestamo> _queryPrestamo_Movimientos(long idPrestamo) {
        synchronized (this) {
            if (prestamo_MovimientosQuery == null) {
                QueryBuilder<detallePrestamo> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdPrestamo.eq(null));
                prestamo_MovimientosQuery = queryBuilder.build();
            }
        }
        Query<detallePrestamo> query = prestamo_MovimientosQuery.forCurrentThread();
        query.setParameter(0, idPrestamo);
        return query.list();
    }

    /** Internal query to resolve the "prestamos" to-many relationship of Movimiento. */
    public List<detallePrestamo> _queryMovimiento_Prestamos(long idMovimiento) {
        synchronized (this) {
            if (movimiento_PrestamosQuery == null) {
                QueryBuilder<detallePrestamo> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdMovimiento.eq(null));
                movimiento_PrestamosQuery = queryBuilder.build();
            }
        }
        Query<detallePrestamo> query = movimiento_PrestamosQuery.forCurrentThread();
        query.setParameter(0, idMovimiento);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPrestamoDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getMovimientoDao().getAllColumns());
            builder.append(" FROM DETALLE_PRESTAMO T");
            builder.append(" LEFT JOIN PRESTAMO T0 ON T.'ID_PRESTAMO'=T0.'_id'");
            builder.append(" LEFT JOIN MOVIMIENTO T1 ON T.'ID_PRESTAMO'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected detallePrestamo loadCurrentDeep(Cursor cursor, boolean lock) {
        detallePrestamo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Prestamo prestamo = loadCurrentOther(daoSession.getPrestamoDao(), cursor, offset);
         if(prestamo != null) {
            entity.setPrestamo(prestamo);
        }
        offset += daoSession.getPrestamoDao().getAllColumns().length;

        Movimiento movimiento = loadCurrentOther(daoSession.getMovimientoDao(), cursor, offset);
         if(movimiento != null) {
            entity.setMovimiento(movimiento);
        }

        return entity;    
    }

    public detallePrestamo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<detallePrestamo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<detallePrestamo> list = new ArrayList<detallePrestamo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<detallePrestamo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<detallePrestamo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
