package com.ernesto.perez.balancepersonal.daos;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.ernesto.perez.balancepersonal.entidades.Movimiento;

import com.ernesto.perez.balancepersonal.entidades.DetalleMovPeriodico;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DETALLE_MOV_PERIODICO.
*/
public class DetalleMovPeriodicoDao extends AbstractDao<DetalleMovPeriodico, Long> {

    public static final String TABLENAME = "DETALLE_MOV_PERIODICO";

    /**
     * Properties of entity DetalleMovPeriodico.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdMovPeriodico = new Property(1, long.class, "idMovPeriodico", false, "ID_MOV_PERIODICO");
        public final static Property IdMovimiento = new Property(2, long.class, "idMovimiento", false, "ID_MOVIMIENTO");
    };

    private DaoSession daoSession;

    private Query<DetalleMovPeriodico> movimientoPeriodico_DetalleMovimientoPeriodicoQuery;

    public DetalleMovPeriodicoDao(DaoConfig config) {
        super(config);
    }
    
    public DetalleMovPeriodicoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DETALLE_MOV_PERIODICO' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'ID_MOV_PERIODICO' INTEGER NOT NULL ," + // 1: idMovPeriodico
                "'ID_MOVIMIENTO' INTEGER NOT NULL );"); // 2: idMovimiento
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DETALLE_MOV_PERIODICO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DetalleMovPeriodico entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIdMovPeriodico());
        stmt.bindLong(3, entity.getIdMovimiento());
    }

    @Override
    protected void attachEntity(DetalleMovPeriodico entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DetalleMovPeriodico readEntity(Cursor cursor, int offset) {
        DetalleMovPeriodico entity = new DetalleMovPeriodico( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // idMovPeriodico
            cursor.getLong(offset + 2) // idMovimiento
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DetalleMovPeriodico entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdMovPeriodico(cursor.getLong(offset + 1));
        entity.setIdMovimiento(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DetalleMovPeriodico entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DetalleMovPeriodico entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "detalleMovimientoPeriodico" to-many relationship of MovimientoPeriodico. */
    public List<DetalleMovPeriodico> _queryMovimientoPeriodico_DetalleMovimientoPeriodico(long idMovPeriodico) {
        synchronized (this) {
            if (movimientoPeriodico_DetalleMovimientoPeriodicoQuery == null) {
                QueryBuilder<DetalleMovPeriodico> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdMovPeriodico.eq(null));
                movimientoPeriodico_DetalleMovimientoPeriodicoQuery = queryBuilder.build();
            }
        }
        Query<DetalleMovPeriodico> query = movimientoPeriodico_DetalleMovimientoPeriodicoQuery.forCurrentThread();
        query.setParameter(0, idMovPeriodico);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMovimientoDao().getAllColumns());
            builder.append(" FROM DETALLE_MOV_PERIODICO T");
            builder.append(" LEFT JOIN MOVIMIENTO T0 ON T.'ID_MOVIMIENTO'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DetalleMovPeriodico loadCurrentDeep(Cursor cursor, boolean lock) {
        DetalleMovPeriodico entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Movimiento movimiento = loadCurrentOther(daoSession.getMovimientoDao(), cursor, offset);
         if(movimiento != null) {
            entity.setMovimiento(movimiento);
        }

        return entity;    
    }

    public DetalleMovPeriodico loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DetalleMovPeriodico> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DetalleMovPeriodico> list = new ArrayList<DetalleMovPeriodico>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DetalleMovPeriodico> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DetalleMovPeriodico> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
