package com.ernesto.perez.balancepersonal.daos;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.ernesto.perez.balancepersonal.entidades.Ajuste;
import com.ernesto.perez.balancepersonal.entidades.Movimiento;

import com.ernesto.perez.balancepersonal.entidades.detalleAjuste;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DETALLE_AJUSTE.
*/
public class detalleAjusteDao extends AbstractDao<detalleAjuste, Long> {

    public static final String TABLENAME = "DETALLE_AJUSTE";

    /**
     * Properties of entity detalleAjuste.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdAjuste = new Property(1, long.class, "idAjuste", false, "ID_AJUSTE");
        public final static Property IdMovimiento = new Property(2, long.class, "idMovimiento", false, "ID_MOVIMIENTO");
    };

    private DaoSession daoSession;

    private Query<detalleAjuste> ajuste_MovimientosQuery;
    private Query<detalleAjuste> movimiento_AjustesQuery;

    public detalleAjusteDao(DaoConfig config) {
        super(config);
    }
    
    public detalleAjusteDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DETALLE_AJUSTE' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'ID_AJUSTE' INTEGER NOT NULL ," + // 1: idAjuste
                "'ID_MOVIMIENTO' INTEGER NOT NULL );"); // 2: idMovimiento
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DETALLE_AJUSTE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, detalleAjuste entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIdAjuste());
        stmt.bindLong(3, entity.getIdMovimiento());
    }

    @Override
    protected void attachEntity(detalleAjuste entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public detalleAjuste readEntity(Cursor cursor, int offset) {
        detalleAjuste entity = new detalleAjuste( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // idAjuste
            cursor.getLong(offset + 2) // idMovimiento
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, detalleAjuste entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdAjuste(cursor.getLong(offset + 1));
        entity.setIdMovimiento(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(detalleAjuste entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(detalleAjuste entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "movimientos" to-many relationship of Ajuste. */
    public List<detalleAjuste> _queryAjuste_Movimientos(long idAjuste) {
        synchronized (this) {
            if (ajuste_MovimientosQuery == null) {
                QueryBuilder<detalleAjuste> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdAjuste.eq(null));
                ajuste_MovimientosQuery = queryBuilder.build();
            }
        }
        Query<detalleAjuste> query = ajuste_MovimientosQuery.forCurrentThread();
        query.setParameter(0, idAjuste);
        return query.list();
    }

    /** Internal query to resolve the "ajustes" to-many relationship of Movimiento. */
    public List<detalleAjuste> _queryMovimiento_Ajustes(long idMovimiento) {
        synchronized (this) {
            if (movimiento_AjustesQuery == null) {
                QueryBuilder<detalleAjuste> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdMovimiento.eq(null));
                movimiento_AjustesQuery = queryBuilder.build();
            }
        }
        Query<detalleAjuste> query = movimiento_AjustesQuery.forCurrentThread();
        query.setParameter(0, idMovimiento);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAjusteDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getMovimientoDao().getAllColumns());
            builder.append(" FROM DETALLE_AJUSTE T");
            builder.append(" LEFT JOIN AJUSTE T0 ON T.'ID_AJUSTE'=T0.'_id'");
            builder.append(" LEFT JOIN MOVIMIENTO T1 ON T.'ID_AJUSTE'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected detalleAjuste loadCurrentDeep(Cursor cursor, boolean lock) {
        detalleAjuste entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Ajuste ajuste = loadCurrentOther(daoSession.getAjusteDao(), cursor, offset);
         if(ajuste != null) {
            entity.setAjuste(ajuste);
        }
        offset += daoSession.getAjusteDao().getAllColumns().length;

        Movimiento movimiento = loadCurrentOther(daoSession.getMovimientoDao(), cursor, offset);
         if(movimiento != null) {
            entity.setMovimiento(movimiento);
        }

        return entity;    
    }

    public detalleAjuste loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<detalleAjuste> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<detalleAjuste> list = new ArrayList<detalleAjuste>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<detalleAjuste> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<detalleAjuste> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
