package com.ernesto.perez.balancepersonal.daos;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.ernesto.perez.balancepersonal.datos.entidades.ImagenD;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table IMAGEN_D.
*/
public class ImagenDDao extends AbstractDao<ImagenD, Long> {

    public static final String TABLENAME = "IMAGEN_D";

    /**
     * Properties of entity ImagenD.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DireccionFisica = new Property(1, String.class, "direccionFisica", false, "DIRECCION_FISICA");
        public final static Property TipoImagen = new Property(2, int.class, "tipoImagen", false, "TIPO_IMAGEN");
        public final static Property Nombre = new Property(3, String.class, "nombre", false, "NOMBRE");
    };

    private DaoSession daoSession;


    public ImagenDDao(DaoConfig config) {
        super(config);
    }
    
    public ImagenDDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'IMAGEN_D' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'DIRECCION_FISICA' TEXT," + // 1: direccionFisica
                "'TIPO_IMAGEN' INTEGER NOT NULL ," + // 2: tipoImagen
                "'NOMBRE' TEXT NOT NULL );"); // 3: nombre
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'IMAGEN_D'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ImagenD entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String direccionFisica = entity.getDireccionFisica();
        if (direccionFisica != null) {
            stmt.bindString(2, direccionFisica);
        }
        stmt.bindLong(3, entity.getTipoImagen());
        stmt.bindString(4, entity.getNombre());
    }

    @Override
    protected void attachEntity(ImagenD entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ImagenD readEntity(Cursor cursor, int offset) {
        ImagenD entity = new ImagenD( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // direccionFisica
            cursor.getInt(offset + 2), // tipoImagen
            cursor.getString(offset + 3) // nombre
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ImagenD entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDireccionFisica(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTipoImagen(cursor.getInt(offset + 2));
        entity.setNombre(cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ImagenD entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ImagenD entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
