package com.ernesto.perez.balancepersonal.daos;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.ernesto.perez.balancepersonal.datos.entidades.AdjuntoD;
import com.ernesto.perez.balancepersonal.datos.entidades.AnulacionMovD;
import com.ernesto.perez.balancepersonal.datos.entidades.CategoriaD;
import com.ernesto.perez.balancepersonal.datos.entidades.OrigenFinancieroD;

import com.ernesto.perez.balancepersonal.datos.entidades.MovimientoD;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MOVIMIENTO_D.
*/
public class MovimientoDDao extends AbstractDao<MovimientoD, Long> {

    public static final String TABLENAME = "MOVIMIENTO_D";

    /**
     * Properties of entity MovimientoD.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Concepto = new Property(1, String.class, "concepto", false, "CONCEPTO");
        public final static Property FechaHora = new Property(2, java.util.Date.class, "fechaHora", false, "FECHA_HORA");
        public final static Property Latitud = new Property(3, double.class, "latitud", false, "LATITUD");
        public final static Property Longitud = new Property(4, double.class, "longitud", false, "LONGITUD");
        public final static Property TipoMovimiento = new Property(5, int.class, "tipoMovimiento", false, "TIPO_MOVIMIENTO");
        public final static Property Importe = new Property(6, double.class, "importe", false, "IMPORTE");
        public final static Property IdCategoria = new Property(7, long.class, "idCategoria", false, "ID_CATEGORIA");
        public final static Property IdOrigenFinanciero = new Property(8, long.class, "idOrigenFinanciero", false, "ID_ORIGEN_FINANCIERO");
        public final static Property IdAnulacion = new Property(9, Long.class, "idAnulacion", false, "ID_ANULACION");
        public final static Property IdAdjunto = new Property(10, Long.class, "idAdjunto", false, "ID_ADJUNTO");
    };

    private DaoSession daoSession;

    private Query<MovimientoD> categoriaD_MovimientosQuery;
    private Query<MovimientoD> origenFinancieroD_OrigenFinancieroQuery;

    public MovimientoDDao(DaoConfig config) {
        super(config);
    }
    
    public MovimientoDDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MOVIMIENTO_D' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'CONCEPTO' TEXT NOT NULL ," + // 1: concepto
                "'FECHA_HORA' INTEGER NOT NULL ," + // 2: fechaHora
                "'LATITUD' REAL NOT NULL ," + // 3: latitud
                "'LONGITUD' REAL NOT NULL ," + // 4: longitud
                "'TIPO_MOVIMIENTO' INTEGER NOT NULL ," + // 5: tipoMovimiento
                "'IMPORTE' REAL NOT NULL ," + // 6: importe
                "'ID_CATEGORIA' INTEGER NOT NULL ," + // 7: idCategoria
                "'ID_ORIGEN_FINANCIERO' INTEGER NOT NULL ," + // 8: idOrigenFinanciero
                "'ID_ANULACION' INTEGER," + // 9: idAnulacion
                "'ID_ADJUNTO' INTEGER);"); // 10: idAdjunto
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MOVIMIENTO_D'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MovimientoD entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getConcepto());
        stmt.bindLong(3, entity.getFechaHora().getTime());
        stmt.bindDouble(4, entity.getLatitud());
        stmt.bindDouble(5, entity.getLongitud());
        stmt.bindLong(6, entity.getTipoMovimiento());
        stmt.bindDouble(7, entity.getImporte());
        stmt.bindLong(8, entity.getIdCategoria());
        stmt.bindLong(9, entity.getIdOrigenFinanciero());
 
        Long idAnulacion = entity.getIdAnulacion();
        if (idAnulacion != null) {
            stmt.bindLong(10, idAnulacion);
        }
 
        Long idAdjunto = entity.getIdAdjunto();
        if (idAdjunto != null) {
            stmt.bindLong(11, idAdjunto);
        }
    }

    @Override
    protected void attachEntity(MovimientoD entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MovimientoD readEntity(Cursor cursor, int offset) {
        MovimientoD entity = new MovimientoD( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // concepto
            new java.util.Date(cursor.getLong(offset + 2)), // fechaHora
            cursor.getDouble(offset + 3), // latitud
            cursor.getDouble(offset + 4), // longitud
            cursor.getInt(offset + 5), // tipoMovimiento
            cursor.getDouble(offset + 6), // importe
            cursor.getLong(offset + 7), // idCategoria
            cursor.getLong(offset + 8), // idOrigenFinanciero
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9), // idAnulacion
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10) // idAdjunto
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MovimientoD entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setConcepto(cursor.getString(offset + 1));
        entity.setFechaHora(new java.util.Date(cursor.getLong(offset + 2)));
        entity.setLatitud(cursor.getDouble(offset + 3));
        entity.setLongitud(cursor.getDouble(offset + 4));
        entity.setTipoMovimiento(cursor.getInt(offset + 5));
        entity.setImporte(cursor.getDouble(offset + 6));
        entity.setIdCategoria(cursor.getLong(offset + 7));
        entity.setIdOrigenFinanciero(cursor.getLong(offset + 8));
        entity.setIdAnulacion(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
        entity.setIdAdjunto(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MovimientoD entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(MovimientoD entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "movimientos" to-many relationship of CategoriaD. */
    public List<MovimientoD> _queryCategoriaD_Movimientos(long idCategoria) {
        synchronized (this) {
            if (categoriaD_MovimientosQuery == null) {
                QueryBuilder<MovimientoD> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdCategoria.eq(null));
                categoriaD_MovimientosQuery = queryBuilder.build();
            }
        }
        Query<MovimientoD> query = categoriaD_MovimientosQuery.forCurrentThread();
        query.setParameter(0, idCategoria);
        return query.list();
    }

    /** Internal query to resolve the "origenFinanciero" to-many relationship of OrigenFinancieroD. */
    public List<MovimientoD> _queryOrigenFinancieroD_OrigenFinanciero(long idOrigenFinanciero) {
        synchronized (this) {
            if (origenFinancieroD_OrigenFinancieroQuery == null) {
                QueryBuilder<MovimientoD> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdOrigenFinanciero.eq(null));
                origenFinancieroD_OrigenFinancieroQuery = queryBuilder.build();
            }
        }
        Query<MovimientoD> query = origenFinancieroD_OrigenFinancieroQuery.forCurrentThread();
        query.setParameter(0, idOrigenFinanciero);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAnulacionMovDDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getAdjuntoDDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getCategoriaDDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T3", daoSession.getOrigenFinancieroDDao().getAllColumns());
            builder.append(" FROM MOVIMIENTO_D T");
            builder.append(" LEFT JOIN ANULACION_MOV_D T0 ON T.'ID_ANULACION'=T0.'_id'");
            builder.append(" LEFT JOIN ADJUNTO_D T1 ON T.'ID_ADJUNTO'=T1.'_id'");
            builder.append(" LEFT JOIN CATEGORIA_D T2 ON T.'ID_CATEGORIA'=T2.'_id'");
            builder.append(" LEFT JOIN ORIGEN_FINANCIERO_D T3 ON T.'ID_ORIGEN_FINANCIERO'=T3.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected MovimientoD loadCurrentDeep(Cursor cursor, boolean lock) {
        MovimientoD entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        AnulacionMovD anulacion = loadCurrentOther(daoSession.getAnulacionMovDDao(), cursor, offset);
        entity.setAnulacion(anulacion);
        offset += daoSession.getAnulacionMovDDao().getAllColumns().length;

        AdjuntoD adjunto = loadCurrentOther(daoSession.getAdjuntoDDao(), cursor, offset);
        entity.setAdjunto(adjunto);
        offset += daoSession.getAdjuntoDDao().getAllColumns().length;

        CategoriaD categoria = loadCurrentOther(daoSession.getCategoriaDDao(), cursor, offset);
         if(categoria != null) {
            entity.setCategoria(categoria);
        }
        offset += daoSession.getCategoriaDDao().getAllColumns().length;

        OrigenFinancieroD movimientos = loadCurrentOther(daoSession.getOrigenFinancieroDDao(), cursor, offset);
         if(movimientos != null) {
            entity.setMovimientos(movimientos);
        }

        return entity;    
    }

    public MovimientoD loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<MovimientoD> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<MovimientoD> list = new ArrayList<MovimientoD>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<MovimientoD> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<MovimientoD> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
