package com.ernesto.perez.balancepersonal.daos;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.ernesto.perez.balancepersonal.entidades.Categoria;
import com.ernesto.perez.balancepersonal.entidades.OrigenFinanciero;

import com.ernesto.perez.balancepersonal.entidades.MovimientoPeriodico;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MOVIMIENTO_PERIODICO.
*/
public class MovimientoPeriodicoDao extends AbstractDao<MovimientoPeriodico, Long> {

    public static final String TABLENAME = "MOVIMIENTO_PERIODICO";

    /**
     * Properties of entity MovimientoPeriodico.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FechaModificacion = new Property(1, java.util.Date.class, "fechaModificacion", false, "FECHA_MODIFICACION");
        public final static Property Intervalo = new Property(2, int.class, "intervalo", false, "INTERVALO");
        public final static Property Estado = new Property(3, int.class, "estado", false, "ESTADO");
        public final static Property Monto = new Property(4, double.class, "monto", false, "MONTO");
        public final static Property IdCategoria = new Property(5, long.class, "idCategoria", false, "ID_CATEGORIA");
        public final static Property IdOrigenFinanciero = new Property(6, long.class, "idOrigenFinanciero", false, "ID_ORIGEN_FINANCIERO");
        public final static Property IdMovPeriodico = new Property(7, long.class, "idMovPeriodico", false, "ID_MOV_PERIODICO");
    };

    private DaoSession daoSession;

    private Query<MovimientoPeriodico> categoria_MovimientosPeriodicosQuery;
    private Query<MovimientoPeriodico> origenFinanciero_MovimientosPeriodicosQuery;
    private Query<MovimientoPeriodico> detalleMovPeriodico_MovimientoPeriodicoQuery;

    public MovimientoPeriodicoDao(DaoConfig config) {
        super(config);
    }
    
    public MovimientoPeriodicoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MOVIMIENTO_PERIODICO' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'FECHA_MODIFICACION' INTEGER NOT NULL ," + // 1: fechaModificacion
                "'INTERVALO' INTEGER NOT NULL ," + // 2: intervalo
                "'ESTADO' INTEGER NOT NULL ," + // 3: estado
                "'MONTO' REAL NOT NULL ," + // 4: monto
                "'ID_CATEGORIA' INTEGER NOT NULL ," + // 5: idCategoria
                "'ID_ORIGEN_FINANCIERO' INTEGER NOT NULL ," + // 6: idOrigenFinanciero
                "'ID_MOV_PERIODICO' INTEGER NOT NULL );"); // 7: idMovPeriodico
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MOVIMIENTO_PERIODICO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MovimientoPeriodico entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getFechaModificacion().getTime());
        stmt.bindLong(3, entity.getIntervalo());
        stmt.bindLong(4, entity.getEstado());
        stmt.bindDouble(5, entity.getMonto());
        stmt.bindLong(6, entity.getIdCategoria());
        stmt.bindLong(7, entity.getIdOrigenFinanciero());
    }

    @Override
    protected void attachEntity(MovimientoPeriodico entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MovimientoPeriodico readEntity(Cursor cursor, int offset) {
        MovimientoPeriodico entity = new MovimientoPeriodico( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            new java.util.Date(cursor.getLong(offset + 1)), // fechaModificacion
            cursor.getInt(offset + 2), // intervalo
            cursor.getInt(offset + 3), // estado
            cursor.getDouble(offset + 4), // monto
            cursor.getLong(offset + 5), // idCategoria
            cursor.getLong(offset + 6) // idOrigenFinanciero
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MovimientoPeriodico entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFechaModificacion(new java.util.Date(cursor.getLong(offset + 1)));
        entity.setIntervalo(cursor.getInt(offset + 2));
        entity.setEstado(cursor.getInt(offset + 3));
        entity.setMonto(cursor.getDouble(offset + 4));
        entity.setIdCategoria(cursor.getLong(offset + 5));
        entity.setIdOrigenFinanciero(cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MovimientoPeriodico entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(MovimientoPeriodico entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "movimientosPeriodicos" to-many relationship of Categoria. */
    public List<MovimientoPeriodico> _queryCategoria_MovimientosPeriodicos(long idOrigenFinanciero) {
        synchronized (this) {
            if (categoria_MovimientosPeriodicosQuery == null) {
                QueryBuilder<MovimientoPeriodico> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdOrigenFinanciero.eq(null));
                categoria_MovimientosPeriodicosQuery = queryBuilder.build();
            }
        }
        Query<MovimientoPeriodico> query = categoria_MovimientosPeriodicosQuery.forCurrentThread();
        query.setParameter(0, idOrigenFinanciero);
        return query.list();
    }

    /** Internal query to resolve the "movimientosPeriodicos" to-many relationship of OrigenFinanciero. */
    public List<MovimientoPeriodico> _queryOrigenFinanciero_MovimientosPeriodicos(long idOrigenFinanciero) {
        synchronized (this) {
            if (origenFinanciero_MovimientosPeriodicosQuery == null) {
                QueryBuilder<MovimientoPeriodico> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdOrigenFinanciero.eq(null));
                origenFinanciero_MovimientosPeriodicosQuery = queryBuilder.build();
            }
        }
        Query<MovimientoPeriodico> query = origenFinanciero_MovimientosPeriodicosQuery.forCurrentThread();
        query.setParameter(0, idOrigenFinanciero);
        return query.list();
    }

    /** Internal query to resolve the "movimientoPeriodico" to-many relationship of DetalleMovPeriodico. */
    public List<MovimientoPeriodico> _queryDetalleMovPeriodico_MovimientoPeriodico(long idMovPeriodico) {
        synchronized (this) {
            if (detalleMovPeriodico_MovimientoPeriodicoQuery == null) {
                QueryBuilder<MovimientoPeriodico> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdMovPeriodico.eq(null));
                detalleMovPeriodico_MovimientoPeriodicoQuery = queryBuilder.build();
            }
        }
        Query<MovimientoPeriodico> query = detalleMovPeriodico_MovimientoPeriodicoQuery.forCurrentThread();
        query.setParameter(0, idMovPeriodico);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCategoriaDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getOrigenFinancieroDao().getAllColumns());
            builder.append(" FROM MOVIMIENTO_PERIODICO T");
            builder.append(" LEFT JOIN CATEGORIA T0 ON T.'ID_CATEGORIA'=T0.'_id'");
            builder.append(" LEFT JOIN ORIGEN_FINANCIERO T1 ON T.'ID_ORIGEN_FINANCIERO'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected MovimientoPeriodico loadCurrentDeep(Cursor cursor, boolean lock) {
        MovimientoPeriodico entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Categoria categoria = loadCurrentOther(daoSession.getCategoriaDao(), cursor, offset);
         if(categoria != null) {
            entity.setCategoria(categoria);
        }
        offset += daoSession.getCategoriaDao().getAllColumns().length;

        OrigenFinanciero origenFinanciero = loadCurrentOther(daoSession.getOrigenFinancieroDao(), cursor, offset);
         if(origenFinanciero != null) {
            entity.setOrigenFinanciero(origenFinanciero);
        }

        return entity;    
    }

    public MovimientoPeriodico loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<MovimientoPeriodico> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<MovimientoPeriodico> list = new ArrayList<MovimientoPeriodico>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<MovimientoPeriodico> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<MovimientoPeriodico> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
