package com.ernesto.perez.balancepersonal.daos;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.ernesto.perez.balancepersonal.entidades.Imagen;

import com.ernesto.perez.balancepersonal.entidades.OrigenFinanciero;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ORIGEN_FINANCIERO.
*/
public class OrigenFinancieroDao extends AbstractDao<OrigenFinanciero, Long> {

    public static final String TABLENAME = "ORIGEN_FINANCIERO";

    /**
     * Properties of entity OrigenFinanciero.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Estado = new Property(1, int.class, "estado", false, "ESTADO");
        public final static Property Nombre = new Property(2, String.class, "nombre", false, "NOMBRE");
        public final static Property Saldo = new Property(3, double.class, "saldo", false, "SALDO");
        public final static Property IdImagen = new Property(4, Long.class, "idImagen", false, "ID_IMAGEN");
    };

    private DaoSession daoSession;


    public OrigenFinancieroDao(DaoConfig config) {
        super(config);
    }
    
    public OrigenFinancieroDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ORIGEN_FINANCIERO' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'ESTADO' INTEGER NOT NULL ," + // 1: estado
                "'NOMBRE' TEXT NOT NULL ," + // 2: nombre
                "'SALDO' REAL NOT NULL ," + // 3: saldo
                "'ID_IMAGEN' INTEGER);"); // 4: idImagen
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ORIGEN_FINANCIERO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, OrigenFinanciero entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getEstado());
        stmt.bindString(3, entity.getNombre());
        stmt.bindDouble(4, entity.getSaldo());
 
        Long idImagen = entity.getIdImagen();
        if (idImagen != null) {
            stmt.bindLong(5, idImagen);
        }
    }

    @Override
    protected void attachEntity(OrigenFinanciero entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public OrigenFinanciero readEntity(Cursor cursor, int offset) {
        OrigenFinanciero entity = new OrigenFinanciero( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // estado
            cursor.getString(offset + 2), // nombre
            cursor.getDouble(offset + 3), // saldo
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // idImagen
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, OrigenFinanciero entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEstado(cursor.getInt(offset + 1));
        entity.setNombre(cursor.getString(offset + 2));
        entity.setSaldo(cursor.getDouble(offset + 3));
        entity.setIdImagen(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(OrigenFinanciero entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(OrigenFinanciero entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getImagenDao().getAllColumns());
            builder.append(" FROM ORIGEN_FINANCIERO T");
            builder.append(" LEFT JOIN IMAGEN T0 ON T.'ID_IMAGEN'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected OrigenFinanciero loadCurrentDeep(Cursor cursor, boolean lock) {
        OrigenFinanciero entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Imagen logo = loadCurrentOther(daoSession.getImagenDao(), cursor, offset);
        entity.setLogo(logo);

        return entity;    
    }

    public OrigenFinanciero loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<OrigenFinanciero> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<OrigenFinanciero> list = new ArrayList<OrigenFinanciero>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<OrigenFinanciero> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<OrigenFinanciero> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
