package com.ernesto.perez.balancepersonal.daos;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.ernesto.perez.balancepersonal.entidades.Contacto;

import com.ernesto.perez.balancepersonal.entidades.Prestamo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PRESTAMO.
*/
public class PrestamoDao extends AbstractDao<Prestamo, Long> {

    public static final String TABLENAME = "PRESTAMO";

    /**
     * Properties of entity Prestamo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FechaHora = new Property(1, java.util.Date.class, "fechaHora", false, "FECHA_HORA");
        public final static Property Monto = new Property(2, double.class, "monto", false, "MONTO");
        public final static Property Estado = new Property(3, int.class, "estado", false, "ESTADO");
        public final static Property Saldo = new Property(4, double.class, "saldo", false, "SALDO");
        public final static Property MontoPagado = new Property(5, double.class, "montoPagado", false, "MONTO_PAGADO");
        public final static Property IdContacto = new Property(6, long.class, "idContacto", false, "ID_CONTACTO");
    };

    private DaoSession daoSession;

    private Query<Prestamo> contacto_PrestamosQuery;

    public PrestamoDao(DaoConfig config) {
        super(config);
    }
    
    public PrestamoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PRESTAMO' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'FECHA_HORA' INTEGER NOT NULL ," + // 1: fechaHora
                "'MONTO' REAL NOT NULL ," + // 2: monto
                "'ESTADO' INTEGER NOT NULL ," + // 3: estado
                "'SALDO' REAL NOT NULL ," + // 4: saldo
                "'MONTO_PAGADO' REAL NOT NULL ," + // 5: montoPagado
                "'ID_CONTACTO' INTEGER NOT NULL );"); // 6: idContacto
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PRESTAMO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Prestamo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getFechaHora().getTime());
        stmt.bindDouble(3, entity.getMonto());
        stmt.bindLong(4, entity.getEstado());
        stmt.bindDouble(5, entity.getSaldo());
        stmt.bindDouble(6, entity.getMontoPagado());
        stmt.bindLong(7, entity.getIdContacto());
    }

    @Override
    protected void attachEntity(Prestamo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Prestamo readEntity(Cursor cursor, int offset) {
        Prestamo entity = new Prestamo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            new java.util.Date(cursor.getLong(offset + 1)), // fechaHora
            cursor.getDouble(offset + 2), // monto
            cursor.getInt(offset + 3), // estado
            cursor.getDouble(offset + 4), // saldo
            cursor.getDouble(offset + 5), // montoPagado
            cursor.getLong(offset + 6) // idContacto
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Prestamo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFechaHora(new java.util.Date(cursor.getLong(offset + 1)));
        entity.setMonto(cursor.getDouble(offset + 2));
        entity.setEstado(cursor.getInt(offset + 3));
        entity.setSaldo(cursor.getDouble(offset + 4));
        entity.setMontoPagado(cursor.getDouble(offset + 5));
        entity.setIdContacto(cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Prestamo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Prestamo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "prestamos" to-many relationship of Contacto. */
    public List<Prestamo> _queryContacto_Prestamos(long idContacto) {
        synchronized (this) {
            if (contacto_PrestamosQuery == null) {
                QueryBuilder<Prestamo> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdContacto.eq(null));
                contacto_PrestamosQuery = queryBuilder.build();
            }
        }
        Query<Prestamo> query = contacto_PrestamosQuery.forCurrentThread();
        query.setParameter(0, idContacto);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getContactoDao().getAllColumns());
            builder.append(" FROM PRESTAMO T");
            builder.append(" LEFT JOIN CONTACTO T0 ON T.'ID_CONTACTO'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Prestamo loadCurrentDeep(Cursor cursor, boolean lock) {
        Prestamo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Contacto contacto = loadCurrentOther(daoSession.getContactoDao(), cursor, offset);
         if(contacto != null) {
            entity.setContacto(contacto);
        }

        return entity;    
    }

    public Prestamo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Prestamo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Prestamo> list = new ArrayList<Prestamo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Prestamo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Prestamo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
