package com.ernesto.perez.balancepersonal.daos;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.ernesto.perez.balancepersonal.entidades.Contacto;

import com.ernesto.perez.balancepersonal.entidades.Telefono;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TELEFONO.
*/
public class TelefonoDao extends AbstractDao<Telefono, Long> {

    public static final String TABLENAME = "TELEFONO";

    /**
     * Properties of entity Telefono.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Telefono = new Property(1, String.class, "telefono", false, "TELEFONO");
        public final static Property IdContacto = new Property(2, long.class, "idContacto", false, "ID_CONTACTO");
    };

    private DaoSession daoSession;

    private Query<Telefono> contacto_TelefonosQuery;

    public TelefonoDao(DaoConfig config) {
        super(config);
    }
    
    public TelefonoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TELEFONO' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'TELEFONO' TEXT NOT NULL ," + // 1: telefono
                "'ID_CONTACTO' INTEGER NOT NULL );"); // 2: idContacto
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TELEFONO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Telefono entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTelefono());
        stmt.bindLong(3, entity.getIdContacto());
    }

    @Override
    protected void attachEntity(Telefono entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Telefono readEntity(Cursor cursor, int offset) {
        Telefono entity = new Telefono( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // telefono
            cursor.getLong(offset + 2) // idContacto
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Telefono entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTelefono(cursor.getString(offset + 1));
        entity.setIdContacto(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Telefono entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Telefono entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "telefonos" to-many relationship of Contacto. */
    public List<Telefono> _queryContacto_Telefonos(long idContacto) {
        synchronized (this) {
            if (contacto_TelefonosQuery == null) {
                QueryBuilder<Telefono> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdContacto.eq(null));
                contacto_TelefonosQuery = queryBuilder.build();
            }
        }
        Query<Telefono> query = contacto_TelefonosQuery.forCurrentThread();
        query.setParameter(0, idContacto);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getContactoDao().getAllColumns());
            builder.append(" FROM TELEFONO T");
            builder.append(" LEFT JOIN CONTACTO T0 ON T.'ID_CONTACTO'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Telefono loadCurrentDeep(Cursor cursor, boolean lock) {
        Telefono entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Contacto contacto = loadCurrentOther(daoSession.getContactoDao(), cursor, offset);
         if(contacto != null) {
            entity.setContacto(contacto);
        }

        return entity;    
    }

    public Telefono loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Telefono> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Telefono> list = new ArrayList<Telefono>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Telefono> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Telefono> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
