package com.ernesto.perez.balancepersonal.entidades;

import com.ernesto.perez.balancepersonal.daos.DaoSession;
import de.greenrobot.dao.DaoException;

import com.ernesto.perez.balancepersonal.daos.AdjuntoDao;
import com.ernesto.perez.balancepersonal.daos.ImagenDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ADJUNTO.
 */
public class Adjunto {

    private Long id;
    private String nota;
    private Long idImagen;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient AdjuntoDao myDao;

    private Imagen imagenAdjunta;
    private Long imagenAdjunta__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Adjunto() {
    }

    public Adjunto(Long id) {
        this.id = id;
    }

    public Adjunto(Long id, String nota, Long idImagen) {
        this.id = id;
        this.nota = nota;
        this.idImagen = idImagen;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getAdjuntoDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNota() {
        return nota;
    }

    public void setNota(String nota) {
        this.nota = nota;
    }

    public Long getIdImagen() {
        return idImagen;
    }

    public void setIdImagen(Long idImagen) {
        this.idImagen = idImagen;
    }

    /** To-one relationship, resolved on first access. */
    public Imagen getImagenAdjunta() {
        Long __key = this.idImagen;
        if (imagenAdjunta__resolvedKey == null || !imagenAdjunta__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ImagenDao targetDao = daoSession.getImagenDao();
            Imagen imagenAdjuntaNew = targetDao.load(__key);
            synchronized (this) {
                imagenAdjunta = imagenAdjuntaNew;
            	imagenAdjunta__resolvedKey = __key;
            }
        }
        return imagenAdjunta;
    }

    public void setImagenAdjunta(Imagen imagenAdjunta) {
        synchronized (this) {
            this.imagenAdjunta = imagenAdjunta;
            idImagen = imagenAdjunta == null ? null : imagenAdjunta.getId();
            imagenAdjunta__resolvedKey = idImagen;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
