package com.ernesto.perez.balancepersonal.entidades;

import java.util.List;
import com.ernesto.perez.balancepersonal.daos.DaoSession;
import de.greenrobot.dao.DaoException;

import com.ernesto.perez.balancepersonal.daos.BancoDao;
import com.ernesto.perez.balancepersonal.daos.CuentaDao;
import com.ernesto.perez.balancepersonal.daos.ImagenDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table BANCO.
 */
public class Banco {

    private Long id;
    /** Not-null value. */
    private String nombre;
    private int tipo;
    /** Not-null value. */
    private java.util.Date fechaModificacion;
    private Long idImagen;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient BancoDao myDao;

    private Imagen logo;
    private Long logo__resolvedKey;

    private List<Cuenta> cuentas;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Banco() {
    }

    public Banco(Long id) {
        this.id = id;
    }

    public Banco(Long id, String nombre, int tipo, java.util.Date fechaModificacion, Long idImagen) {
        this.id = id;
        this.nombre = nombre;
        this.tipo = tipo;
        this.fechaModificacion = fechaModificacion;
        this.idImagen = idImagen;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getBancoDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNombre() {
        return nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public int getTipo() {
        return tipo;
    }

    public void setTipo(int tipo) {
        this.tipo = tipo;
    }

    /** Not-null value. */
    public java.util.Date getFechaModificacion() {
        return fechaModificacion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFechaModificacion(java.util.Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    public Long getIdImagen() {
        return idImagen;
    }

    public void setIdImagen(Long idImagen) {
        this.idImagen = idImagen;
    }

    /** To-one relationship, resolved on first access. */
    public Imagen getLogo() {
        Long __key = this.idImagen;
        if (logo__resolvedKey == null || !logo__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ImagenDao targetDao = daoSession.getImagenDao();
            Imagen logoNew = targetDao.load(__key);
            synchronized (this) {
                logo = logoNew;
            	logo__resolvedKey = __key;
            }
        }
        return logo;
    }

    public void setLogo(Imagen logo) {
        synchronized (this) {
            this.logo = logo;
            idImagen = logo == null ? null : logo.getId();
            logo__resolvedKey = idImagen;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Cuenta> getCuentas() {
        if (cuentas == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            CuentaDao targetDao = daoSession.getCuentaDao();
            List<Cuenta> cuentasNew = targetDao._queryBanco_Cuentas(id);
            synchronized (this) {
                if(cuentas == null) {
                    cuentas = cuentasNew;
                }
            }
        }
        return cuentas;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetCuentas() {
        cuentas = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
