package com.ernesto.perez.balancepersonal.entidades;

import com.ernesto.perez.balancepersonal.daos.DaoSession;
import de.greenrobot.dao.DaoException;

import com.ernesto.perez.balancepersonal.daos.AjusteDao;
import com.ernesto.perez.balancepersonal.daos.MovimientoDao;
import com.ernesto.perez.balancepersonal.daos.detalleAjusteDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table DETALLE_AJUSTE.
 */
public class detalleAjuste {

    private Long id;
    private long idAjuste;
    private long idMovimiento;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient detalleAjusteDao myDao;

    private Ajuste ajuste;
    private Long ajuste__resolvedKey;

    private Movimiento movimiento;
    private Long movimiento__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public detalleAjuste() {
    }

    public detalleAjuste(Long id) {
        this.id = id;
    }

    public detalleAjuste(Long id, long idAjuste, long idMovimiento) {
        this.id = id;
        this.idAjuste = idAjuste;
        this.idMovimiento = idMovimiento;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getDetalleAjusteDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getIdAjuste() {
        return idAjuste;
    }

    public void setIdAjuste(long idAjuste) {
        this.idAjuste = idAjuste;
    }

    public long getIdMovimiento() {
        return idMovimiento;
    }

    public void setIdMovimiento(long idMovimiento) {
        this.idMovimiento = idMovimiento;
    }

    /** To-one relationship, resolved on first access. */
    public Ajuste getAjuste() {
        long __key = this.idAjuste;
        if (ajuste__resolvedKey == null || !ajuste__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            AjusteDao targetDao = daoSession.getAjusteDao();
            Ajuste ajusteNew = targetDao.load(__key);
            synchronized (this) {
                ajuste = ajusteNew;
            	ajuste__resolvedKey = __key;
            }
        }
        return ajuste;
    }

    public void setAjuste(Ajuste ajuste) {
        if (ajuste == null) {
            throw new DaoException("To-one property 'idAjuste' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.ajuste = ajuste;
            idAjuste = ajuste.getId();
            ajuste__resolvedKey = idAjuste;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Movimiento getMovimiento() {
        long __key = this.idAjuste;
        if (movimiento__resolvedKey == null || !movimiento__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            MovimientoDao targetDao = daoSession.getMovimientoDao();
            Movimiento movimientoNew = targetDao.load(__key);
            synchronized (this) {
                movimiento = movimientoNew;
            	movimiento__resolvedKey = __key;
            }
        }
        return movimiento;
    }

    public void setMovimiento(Movimiento movimiento) {
        if (movimiento == null) {
            throw new DaoException("To-one property 'idAjuste' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.movimiento = movimiento;
            idAjuste = movimiento.getId();
            movimiento__resolvedKey = idAjuste;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
