package com.ernesto.perez.balancepersonal.entidades;

import java.util.List;
import com.ernesto.perez.balancepersonal.daos.DaoSession;
import de.greenrobot.dao.DaoException;

import com.ernesto.perez.balancepersonal.daos.ImagenDao;
import com.ernesto.perez.balancepersonal.daos.MovimientoDao;
import com.ernesto.perez.balancepersonal.daos.MovimientoPeriodicoDao;
import com.ernesto.perez.balancepersonal.daos.OrigenFinancieroDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ORIGEN_FINANCIERO.
 */
public class OrigenFinanciero {

    private Long id;
    private int estado;
    /** Not-null value. */
    private String nombre;
    private double saldo;
    private Long idImagen;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient OrigenFinancieroDao myDao;

    private Imagen logo;
    private Long logo__resolvedKey;

    private List<Movimiento> origenFinanciero;
    private List<MovimientoPeriodico> movimientosPeriodicos;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public OrigenFinanciero() {
    }

    public OrigenFinanciero(Long id) {
        this.id = id;
    }

    public OrigenFinanciero(Long id, int estado, String nombre, double saldo, Long idImagen) {
        this.id = id;
        this.estado = estado;
        this.nombre = nombre;
        this.saldo = saldo;
        this.idImagen = idImagen;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getOrigenFinancieroDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getEstado() {
        return estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    /** Not-null value. */
    public String getNombre() {
        return nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public double getSaldo() {
        return saldo;
    }

    public void setSaldo(double saldo) {
        this.saldo = saldo;
    }

    public Long getIdImagen() {
        return idImagen;
    }

    public void setIdImagen(Long idImagen) {
        this.idImagen = idImagen;
    }

    /** To-one relationship, resolved on first access. */
    public Imagen getLogo() {
        Long __key = this.idImagen;
        if (logo__resolvedKey == null || !logo__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ImagenDao targetDao = daoSession.getImagenDao();
            Imagen logoNew = targetDao.load(__key);
            synchronized (this) {
                logo = logoNew;
            	logo__resolvedKey = __key;
            }
        }
        return logo;
    }

    public void setLogo(Imagen logo) {
        synchronized (this) {
            this.logo = logo;
            idImagen = logo == null ? null : logo.getId();
            logo__resolvedKey = idImagen;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Movimiento> getOrigenFinanciero() {
        if (origenFinanciero == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            MovimientoDao targetDao = daoSession.getMovimientoDao();
            List<Movimiento> origenFinancieroNew = targetDao._queryOrigenFinanciero_OrigenFinanciero(id);
            synchronized (this) {
                if(origenFinanciero == null) {
                    origenFinanciero = origenFinancieroNew;
                }
            }
        }
        return origenFinanciero;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetOrigenFinanciero() {
        origenFinanciero = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<MovimientoPeriodico> getMovimientosPeriodicos() {
        if (movimientosPeriodicos == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            MovimientoPeriodicoDao targetDao = daoSession.getMovimientoPeriodicoDao();
            List<MovimientoPeriodico> movimientosPeriodicosNew = targetDao._queryOrigenFinanciero_MovimientosPeriodicos(id);
            synchronized (this) {
                if(movimientosPeriodicos == null) {
                    movimientosPeriodicos = movimientosPeriodicosNew;
                }
            }
        }
        return movimientosPeriodicos;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetMovimientosPeriodicos() {
        movimientosPeriodicos = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
